### ISSUE TITLE
hrwa_manager:  deploy via puppet?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/hrwa_manager#2]
maybe via jenkins build?

it's currently on `sul-robots3-prod`, probably manaually installed. 

how shall it be installed on new VMs? 

use WASMetadataExtractor.jar  deployment as a model?  (I believe it's a jar with a jenkins build, and a puppet script to get a deploy artifact from jenkins???)

also, are there other was-robot specific things mounted for sul-robots3-prod   that need to come to new was-robot-vms?  cdl-manager?  lockss mount?   @tallenaz will discuss with @nullhandle

**Comment by tallenaz** [comment]
WASMetadataExtractor.jar does have a jenkins build, but it isn't deployed via puppet -- as far as I can see, it just lives in `was_robot_suite/jar` and is updated via git commit. Will try to get clearer today on the status of that jar and the things on the mount, especially how they ought to be installed.

**Comment by tallenaz** [comment]
Had a chat with @nullhandle: `hrwa_manager` is not robots related, nor is anything else in the same directory. `hrwa_manager` instead is a `was-downloader` concern.

**Comment by ndushay** [comment]
ok, Not sure we have to undertake lots of puppet work for `was-downloader` and `hrwa-manager` at this time, but we should make sure they won't disappear when we stop using their mount points on sul-robots3-prod 

- WASMetadataExtractor  needs an update to its devops docs (no puppet in deploy;  prod checklist should at least have TODO boxes to move jenkins build to travis ...)  (see sul-dlss/WASMetadataExtractor/issues/5)
- hrwa_manager: we want at least some better devops docs about hrwa_manager (say it's related to was-downloader, where it lives ...) sul-dlss/hrwa_manager/issues/3
- was-downloader: need some info (at least a readme).  (see sul-dlss/web-archiving/issues/25)

**Comment by ndushay** [comment]
this repo no longer works and we've stopped using it altogether.

**Comment by tallenaz** [comment]
We can move it to https://github.com/sul-dlss-deprecated !
